### ISSUE TITLE
"libcompress.so" is 32-bit instead of 64-bit issue, this file not work in Samsung s6 and OnePlus2 Device.

### ISSUE THREAD

**Issue by rajnitgajera** [yovenny/VideoCompress#1]
com.samuel.OvationTube E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                                                                        Process: com.samuel.OvationTube, PID: 19957
                                                                        java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.UnsatisfiedLinkError: **dlopen failed: "/data/app/package-name/lib/arm64/libcompress.so" is 32-bit instead of 64-bit**
                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                            at java.lang.System.loadLibrary(System.java:1076)
                                                                            at com.yovenny.videocompress.MediaController.<clinit>(MediaController.java:31)
                                                                           

Is there any solution for this problem?

or you send me **"libcompress.so"** file for **64bit** version of **'arm64-v8a'.**

Thanks.

**Comment by kishorejethava** [comment]
Same issue!!!

**Comment by ArtemKumeisha** [comment]
Yeah. I'm facing this issue too. Need libcompress.so  64-bit version of library. Can you help with it, please?

**Comment by Ktirumalsetty** [comment]
found any solution for this?

**Comment by Dnyaneshwar1926** [comment]
Did anyone found a solution for video compress?? Pls help.

**Comment by Ktirumalsetty** [comment]
https://github.com/fishwjy/VideoCompressor use this as an alternate it doesn't have .so files
