### ISSUE TITLE
couldn't find "libcompress.so" Xiaomi mi5 android 7

### ISSUE THREAD

**Issue by AseevEIDev** [yovenny/VideoCompress#3]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ru.mobiledev.badfit-2/base.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_dependencies_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_0_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_1_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_2_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_3_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_4_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_5_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_6_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_7_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_8_apk.apk", zip file "/data/app/ru.mobiledev.badfit-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ru.mobiledev.badfit-2/lib/arm64, /data/app/ru.mobiledev.badfit-2/base.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/ru.mobiledev.badfit-2/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libcompress.so"
                                                                         at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                         at java.lang.System.loadLibrary(System.java:1530)

**Comment by Apples0609** [comment]
v7a下边的so复制到其他cpu架构文件夹下

**Comment by ProMode7** [comment]
Just edit the gradle.properties in the root folder and add android.useDeprecatedNdk=true. Then edit the build.gradle file in your app's folder, set abiFilters as below:

android {
    ....
    defaultConfig {
        ....
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips"
        }
    }
}
